### ISSUE TITLE
至今没装好gentoo，坐等楼主脚本

### ISSUE THREAD

**Issue by lsblk** [YangMame/Gentoo-Installer#1]
手动滑稽

**Comment by YangMame** [comment]
@lsblk 既然有人催了 那我这几天开始写 /滑稽

**Comment by lsblk** [comment]
滑稽

**Comment by YangMame** [comment]
@lsblk 脚本要处理的东西很多 变量也很多 可能要经过比较长的时间编写和测试 慢慢等吧

**Comment by lsblk** [comment]
好的，谢谢啦，，

**Comment by YangMame** [comment]
@lsblk 写好了雏形 你来当白鼠不 /滑稽

**Comment by lsblk** [comment]
吼啊，，正在疯狂的编译
![_deepin-terminal_20170709180458](https://user-images.githubusercontent.com/11588373/27992905-4a8cb220-64d1-11e7-9eed-a4bf70f923d9.gif)

**Comment by YangMame** [comment]
@lsblk 对了 要注意和Arch的grub分开 因为它俩uefi都是直接挂boot 会造成俩者混乱 结果你懂的 /滑稽

**Comment by YangMame** [comment]
@lsblk 编译内核记得选中systemd去掉openrc 要注意的应该就这样了

**Comment by lsblk** [comment]
额，我似乎没有指定/boot分区，所以安装uefi会出错吧，，，

**Comment by YangMame** [comment]
@lsblk 这里的boot指efi分区 可以直接挂载到boot Ubuntu什么的则会帮你指定/boot/efi gentoo和arch不会 所以它们俩会混乱

**Comment by lsblk** [comment]
额，我的习惯是把efi单独挂载比如/f，然后grub-install 指定/f，这样/boot的乱七八糟的文件就不会放到efi分区了，这样efi分区会很简洁，，另外如果我没有提供/boot分区，我没看到你要求输入再次输入efi分区，这样grub-install 时是否会出错？

**Comment by lsblk** [comment]
另外刚才我的终端崩了，，，正在研究怎样中途恢复。。

**Comment by YangMame** [comment]
@lsblk 重新运行脚本把efi挂载到boot或者你自己改改脚本里面的挂载点 看看脚本或许更好

**Comment by YangMame** [comment]
@lsblk 重新chroot进去kill掉emerge

**Comment by lsblk** [comment]
好的，，，谢谢啦

**Comment by YangMame** [comment]
@lsblk 祝玩的愉快 /滑稽

**Comment by YangMame** [comment]
@lsblk 忘了说 没有genfstab就需要自己写/etc/fstab（编译安装内核前需要写好）
具体步骤：blkid命令查看分区的uuid
再照着你现在系统的fstab挂载点添加

**Comment by lsblk** [comment]
好的，不过我安装了arch-install-scripts包了，，谢谢啦

**Comment by YangMame** [comment]
@lsblk 记得提错误和bug /滑稽

**Comment by YangMame** [comment]
后期会加上安装桌面等。。。不过我想你也不需要 看看wiki就好

**Comment by lsblk** [comment]
好的，，不过我水平实在是太渣，，尽力吧，，

**Comment by lsblk** [comment]
嗯嗯

**Comment by lsblk** [comment]
楼主为什么用ubuntu的config啊？为什么不用arch的？

**Comment by YangMame** [comment]
@lsblk arch的编译出来的驱动可能不如Ubuntu的全面 之后会加上 感觉Arch的内核配置更适合台式

**Comment by lsblk** [comment]
哦哦，谢谢解释，，表示对这方面完全不懂，，

**Comment by YangMame** [comment]
@lsblk 今天我也来实体机测试了 发现很多bug /吐血

**Comment by YangMame** [comment]
@lsblk 不介意的话等我补完一波坑再来试试

**Comment by lsblk** [comment]
好的，，我成功的没能启动，，我用的lvm分区，说我的安装分区不是合法的root设备，看来可能哪里没开启lvm选项

**Comment by YangMame** [comment]
@lsblk lvm啊 没玩过 2333

**Comment by YangMame** [comment]
![2017-07-10-115958_1920x1080_scrot](https://user-images.githubusercontent.com/20044469/28002393-59f76c3c-6567-11e7-848b-aef6807fbada.png)
我把Arch的grub换成bootctl 防止和Gentoo冲突
现在测试到编译内核了
至于lvm 官方有说明：https://wiki.gentoo.org/wiki/LVM

**Comment by YangMame** [comment]
@lsblk 我已经测试修改完了 有个要注意的 安装完之后它默认启动Arch的内核。。。所以会造成启动不了系统 开机grub进rec选择gentoo自己的内核启动
